# Generated by Django 3.2.10 on 2022-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('color', models.TextField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
