# Generated by Django 3.2.10 on 2022-01-07 05:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20220106_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemodel',
            name='order',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
