# Generated by Django 3.2.10 on 2022-01-07 06:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_mobilemodel_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_description', tinymce.models.HTMLField(default='')),
            ],
        ),
    ]
